#!/usr/bin/env python3
"""Generate the Linux tray state icons from the Polaris logo.

The tray shows the plain logo while idle (images/logo-polaris.svg, a copy of polaris.svg).
While a stream plays or is paused, and in the notification for an incoming pairing request,
it shows the logo with a corner badge: a play triangle, pause bars or a padlock. This script
writes those three files into the web images, which the tray reads by path and the Linux
package also installs as hicolor status icons:

    python3 scripts/icons/generate-tray-icons.py

The logo paths are copied verbatim from polaris.svg, so rerun this after the logo changes.
Only presentation attributes are used (no masks, clip paths or CSS classes) because Plasma's
tray renders icons given by path through Qt SVG. The badge radius is the smallest that keeps
the pause bars readable at 16 px; the dark ring separates the badge from the logo on dark
panels and from the panel itself on light ones. Colours are the web console's palette.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / 'src_assets/common/assets/web/public/images'

W, H = 713.3, 649.6
LOGO = '#C8D6E5'  # the logo's own fill, the console's --color-ice
VOID = '#2A2840'  # the console's --color-void, for glyphs and the ring
R = 180.0         # badge radius in logo units
RING = 0.2 * R


def fmt(value):
    return f'{value:.1f}'.rstrip('0').rstrip('.')


def main():
    base = (ROOT / 'polaris.svg').read_text()
    if base.count(f'viewBox="0 0 {W} {H}"') != 1:
        sys.exit('polaris.svg: unexpected viewBox; update W and H here first')
    match = re.search(r'<g>\s*(.*?)\s*</g>', base, re.S)
    if not match:
        sys.exit('polaris.svg: the logo group was not found')
    logo = match.group(1).replace(' class="st0"', '')

    outer = R + RING / 2
    cx, cy = W - outer, H - outer
    f = fmt
    glyphs = {
        'playing': ('#4ADE80', 'a stream is playing',
                    f'<path d="M{f(cx - 0.30 * R)} {f(cy - 0.50 * R)}V{f(cy + 0.50 * R)}L{f(cx + 0.56 * R)} {f(cy)}Z" '
                    f'fill="{VOID}" stroke="{VOID}" stroke-width="{f(0.10 * R)}" stroke-linejoin="round"/>'),
        'pausing': ('#FBBF24', 'the stream is paused',
                    f'<rect x="{f(cx - 0.39 * R)}" y="{f(cy - 0.50 * R)}" width="{f(0.26 * R)}" height="{f(R)}" rx="{f(0.05 * R)}" fill="{VOID}"/>'
                    f'<rect x="{f(cx + 0.13 * R)}" y="{f(cy - 0.50 * R)}" width="{f(0.26 * R)}" height="{f(R)}" rx="{f(0.05 * R)}" fill="{VOID}"/>'),
        'locked': ('#38BDF8', 'a device is asking to pair',
                   f'<path d="M{f(cx - 0.25 * R)} {f(cy)}V{f(cy - 0.22 * R)}A{f(0.25 * R)} {f(0.25 * R)} 0 0 1 {f(cx + 0.25 * R)} {f(cy - 0.22 * R)}V{f(cy)}" '
                   f'fill="none" stroke="{VOID}" stroke-width="{f(0.22 * R)}"/>'
                   f'<rect x="{f(cx - 0.42 * R)}" y="{f(cy - 0.02 * R)}" width="{f(0.84 * R)}" height="{f(0.58 * R)}" rx="{f(0.08 * R)}" fill="{VOID}"/>'),
    }
    for state, (badge, meaning, glyph) in glyphs.items():
        svg = (
            '<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Polaris tray icon: {meaning}. Generated by scripts/icons/generate-tray-icons.py from polaris.svg. -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">\n'
            f'<g fill="{LOGO}">\n\t{logo}\n</g>\n'
            f'<circle cx="{f(cx)}" cy="{f(cy)}" r="{f(R)}" fill="{badge}" stroke="{VOID}" stroke-width="{f(RING)}"/>\n'
            f'{glyph}\n'
            '</svg>\n'
        )
        (OUT / f'polaris-{state}.svg').write_text(svg)
        print(f'wrote images/polaris-{state}.svg')


if __name__ == '__main__':
    main()
